"""
Baylor Chess - single-file version.

Everything (board, rules, bots, move history sidebar, timer, coordinates,
resign, coin flip, and game review) lives in this one file. No imports
from ChessBot.py or GameManager.py.

Requires: pip install python-chess pygame
Requires: assets/pieces/*.png already generated by ConvertPieces.py

Run:
    python3 baylor_chess.py

Controls:
    - Click a piece to select it (legal destinations shown as gold dots).
    - Click a highlighted square to move there.
    - Pawns auto-promote to Queen.
    - Left / Right arrow keys: step backward / forward through move history.
    - Click any move in the sidebar list to jump straight to that position.
    - Click "Return to Live" (or press Right until the end) to resume play.
    - Click "Resign" anytime during play to concede.
    - After the game ends, click "Game Review" for a move-by-move breakdown.
"""

import json
import os
import random
import sys
import time

import pygame
import chess

os.chdir(os.path.dirname(os.path.abspath(__file__)))

BOARD_SIZE = 640
SQUARE_SIZE = BOARD_SIZE // 8
STATUS_HEIGHT = 40
SIDEBAR_WIDTH = 280
MENU_WINDOW_SIZE = (BOARD_SIZE, BOARD_SIZE + STATUS_HEIGHT)
GAME_WINDOW_SIZE = (BOARD_SIZE + SIDEBAR_WIDTH, BOARD_SIZE + STATUS_HEIGHT)

BAYLOR_GREEN = (0, 48, 21)
BAYLOR_GOLD = (255, 184, 28)
LIGHT_SQUARE = (255, 244, 214)
DARK_SQUARE = (0, 68, 34)
HIGHLIGHT = (255, 184, 28)
MOVE_DOT = (0, 48, 21)
STATUS_BG = (0, 48, 21)
STATUS_TEXT = (255, 184, 28)
WHITE_TEXT = (255, 255, 255)
SIDEBAR_BG = (0, 38, 17)

GOOD_COLOR = (60, 160, 60)
OK_COLOR = (200, 170, 40)
BAD_COLOR = (190, 60, 60)
SUGGEST_COLOR = (90, 150, 230)

PIECE_DIR = os.path.join("assets", "pieces")

HUMAN_COLOR = chess.WHITE   # you're playing White; flip this to play Black
PIECE_VALUES = {chess.PAWN: 1, chess.KNIGHT: 3, chess.BISHOP: 3, chess.ROOK: 5, chess.QUEEN: 9}

REVIEW_DEPTH = 2
GOOD_THRESHOLD = 30
OK_THRESHOLD = 150

# --- Piece-square tables (from White's point of view, a8 -> h1 reading order) ---
PAWN_PST = [
     0,   0,   0,   0,   0,   0,   0,   0,
    50,  50,  50,  50,  50,  50,  50,  50,
    10,  10,  20,  30,  30,  20,  10,  10,
     5,   5,  10,  25,  25,  10,   5,   5,
     0,   0,   0,  20,  20,   0,   0,   0,
     5,  -5, -10,   0,   0, -10,  -5,   5,
     5,  10,  10, -20, -20,  10,  10,   5,
     0,   0,   0,   0,   0,   0,   0,   0,
]
KNIGHT_PST = [
    -50, -40, -30, -30, -30, -30, -40, -50,
    -40, -20,   0,   0,   0,   0, -20, -40,
    -30,   0,  10,  15,  15,  10,   0, -30,
    -30,   5,  15,  20,  20,  15,   5, -30,
    -30,   0,  15,  20,  20,  15,   0, -30,
    -30,   5,  10,  15,  15,  10,   5, -30,
    -40, -20,   0,   5,   5,   0, -20, -40,
    -50, -40, -30, -30, -30, -30, -40, -50,
]
BISHOP_PST = [
    -20, -10, -10, -10, -10, -10, -10, -20,
    -10,   0,   0,   0,   0,   0,   0, -10,
    -10,   0,   5,  10,  10,   5,   0, -10,
    -10,   5,   5,  10,  10,   5,   5, -10,
    -10,   0,  10,  10,  10,  10,   0, -10,
    -10,  10,  10,  10,  10,  10,  10, -10,
    -10,   5,   0,   0,   0,   0,   5, -10,
    -20, -10, -10, -10, -10, -10, -10, -20,
]
ROOK_PST = [
      0,   0,   0,   0,   0,   0,   0,   0,
      5,  10,  10,  10,  10,  10,  10,   5,
     -5,   0,   0,   0,   0,   0,   0,  -5,
     -5,   0,   0,   0,   0,   0,   0,  -5,
     -5,   0,   0,   0,   0,   0,   0,  -5,
     -5,   0,   0,   0,   0,   0,   0,  -5,
     -5,   0,   0,   0,   0,   0,   0,  -5,
      0,   0,   0,   5,   5,   0,   0,   0,
]
QUEEN_PST = [
    -20, -10, -10,  -5,  -5, -10, -10, -20,
    -10,   0,   0,   0,   0,   0,   0, -10,
    -10,   0,   5,   5,   5,   5,   0, -10,
     -5,   0,   5,   5,   5,   5,   0,  -5,
      0,   0,   5,   5,   5,   5,   0,  -5,
    -10,   5,   5,   5,   5,   5,   0, -10,
    -10,   0,   5,   0,   0,   0,   0, -10,
    -20, -10, -10,  -5,  -5, -10, -10, -20,
]
KING_PST = [
    -30, -40, -40, -50, -50, -40, -40, -30,
    -30, -40, -40, -50, -50, -40, -40, -30,
    -30, -40, -40, -50, -50, -40, -40, -30,
    -30, -40, -40, -50, -50, -40, -40, -30,
    -20, -30, -30, -40, -40, -30, -30, -20,
    -10, -20, -20, -20, -20, -20, -20, -10,
     20,  20,   0,   0,   0,   0,  20,  20,
     20,  30,  10,   0,   0,  10,  30,  20,
]
PST = {
    chess.PAWN: PAWN_PST, chess.KNIGHT: KNIGHT_PST, chess.BISHOP: BISHOP_PST,
    chess.ROOK: ROOK_PST, chess.QUEEN: QUEEN_PST, chess.KING: KING_PST,
}


def pst_value(piece_type, square, color):
    file = chess.square_file(square)
    rank = chess.square_rank(square)
    idx = (7 - rank) * 8 + file if color == chess.WHITE else rank * 8 + file
    return PST[piece_type][idx]


def material_eval(board, color):
    score = 0
    for pt, value in PIECE_VALUES.items():
        score += value * (len(board.pieces(pt, color)) - len(board.pieces(pt, not color)))
    return score


def positional_eval(board, color):
    score = 0
    for square in chess.SQUARES:
        piece = board.piece_at(square)
        if piece is None:
            continue
        value = PIECE_VALUES.get(piece.piece_type, 0) * 100 + pst_value(piece.piece_type, square, piece.color)
        score += value if piece.color == color else -value
    mobility = board.legal_moves.count()
    score += mobility if board.turn == color else -mobility
    return score


def random_move(board):
    return random.choice(list(board.legal_moves))


def minimax(board, depth, color):
    if depth == 0 or board.is_game_over():
        return material_eval(board, color)
    best = float("-inf")
    for move in board.legal_moves:
        board.push(move)
        best = max(best, -minimax(board, depth - 1, not color))
        board.pop()
    return best


def alpha_beta(board, depth, alpha, beta, color, eval_fn):
    if depth == 0 or board.is_game_over():
        return eval_fn(board, color)
    for move in board.legal_moves:
        board.push(move)
        alpha = max(alpha, -alpha_beta(board, depth - 1, -beta, -alpha, not color, eval_fn))
        board.pop()
        if alpha >= beta:
            break
    return alpha


def pick_best_move(board, color, score_after_move):
    best_move, best_score = None, float("-inf")
    for move in board.legal_moves:
        board.push(move)
        score = -score_after_move(board)
        board.pop()
        if score > best_score:
            best_score = score
            best_move = move
    return best_move


def easy_bot_move(board, color):
    return random_move(board)


def medium_bot_move(board, color):
    depth = 2
    return pick_best_move(board, color, lambda b: minimax(b, depth - 1, not color))


def hard_bot_move(board, color):
    depth = 4
    return pick_best_move(
        board, color,
        lambda b: alpha_beta(b, depth - 1, float("-inf"), float("inf"), not color, material_eval),
    )


def bear_bot_move(board, color):
    depth = 4
    return pick_best_move(
        board, color,
        lambda b: alpha_beta(b, depth - 1, float("-inf"), float("inf"), not color, positional_eval),
    )


BOT_MOVE_FUNCS = {
    "Easy": easy_bot_move,
    "Medium": medium_bot_move,
    "Hard": hard_bot_move,
    "Bear": bear_bot_move,
}

DIFFICULTY_INFO = {
    "Easy": "Random legal moves - learning the rules",
    "Medium": "Minimax, thinks 2 moves ahead",
    "Hard": "Alpha-beta pruning, solid tactics",
    "Bear": "Alpha-beta + positional strategy - toughest",
}

CONTROLS_LINES = [
    "Click a piece to select it, click a lit square to move",
    "Left / Right arrows: step through move history",
    "Click any move in the sidebar to jump to that position",
    "Resign anytime from the in-game sidebar",
]

PIECE_NAME_MAP = {
    (chess.WHITE, chess.PAWN): "wP", (chess.WHITE, chess.ROOK): "wR",
    (chess.WHITE, chess.KNIGHT): "wN", (chess.WHITE, chess.BISHOP): "wB",
    (chess.WHITE, chess.QUEEN): "wQ", (chess.WHITE, chess.KING): "wK",
    (chess.BLACK, chess.PAWN): "bP", (chess.BLACK, chess.ROOK): "bR",
    (chess.BLACK, chess.KNIGHT): "bN", (chess.BLACK, chess.BISHOP): "bB",
    (chess.BLACK, chess.QUEEN): "bQ", (chess.BLACK, chess.KING): "bK",
}


def load_piece_images(size):
    images = {}
    for key, name in PIECE_NAME_MAP.items():
        path = os.path.join(PIECE_DIR, f"{name}.png")
        img = pygame.image.load(path).convert_alpha()
        images[key] = pygame.transform.smoothscale(img, (size, size))
    return images


def square_to_pixel(square):
    file = chess.square_file(square)
    rank = chess.square_rank(square)
    if HUMAN_COLOR == chess.BLACK:
        col, row = 7 - file, rank
    else:
        col, row = file, 7 - rank
    return col * SQUARE_SIZE, row * SQUARE_SIZE


def pixel_to_square(pos):
    x, y = pos
    if y >= BOARD_SIZE or x >= BOARD_SIZE:
        return None
    col, row = x // SQUARE_SIZE, y // SQUARE_SIZE
    if HUMAN_COLOR == chess.BLACK:
        file, rank = 7 - col, row
    else:
        file, rank = col, 7 - row
    return chess.square(file, rank)


def draw_board(screen, view_board, images, selected_square, legal_targets):
    for rank in range(8):
        for file in range(8):
            square = chess.square(file, rank)
            x, y = square_to_pixel(square)
            is_light = (file + rank) % 2 == 1
            color = LIGHT_SQUARE if is_light else DARK_SQUARE
            pygame.draw.rect(screen, color, (x, y, SQUARE_SIZE, SQUARE_SIZE))

    if selected_square is not None:
        x, y = square_to_pixel(selected_square)
        pygame.draw.rect(screen, HIGHLIGHT, (x, y, SQUARE_SIZE, SQUARE_SIZE), 4)

    for target in legal_targets:
        x, y = square_to_pixel(target)
        center = (x + SQUARE_SIZE // 2, y + SQUARE_SIZE // 2)
        pygame.draw.circle(screen, MOVE_DOT, center, 10)

    for square in chess.SQUARES:
        piece = view_board.piece_at(square)
        if piece:
            x, y = square_to_pixel(square)
            screen.blit(images[(piece.color, piece.piece_type)], (x, y))


FILE_LETTERS = "abcdefgh"


def draw_coordinates(screen, small_font):
    for col in range(8):
        square = pixel_to_square((col * SQUARE_SIZE + SQUARE_SIZE // 2, 7 * SQUARE_SIZE + SQUARE_SIZE // 2))
        file = chess.square_file(square)
        rank = chess.square_rank(square)
        is_light = (file + rank) % 2 == 1
        color = DARK_SQUARE if is_light else LIGHT_SQUARE
        label = small_font.render(FILE_LETTERS[file], True, color)
        x = col * SQUARE_SIZE + SQUARE_SIZE - label.get_width() - 4
        y = BOARD_SIZE - label.get_height() - 2
        screen.blit(label, (x, y))

    for row in range(8):
        square = pixel_to_square((SQUARE_SIZE // 2, row * SQUARE_SIZE + SQUARE_SIZE // 2))
        file = chess.square_file(square)
        rank = chess.square_rank(square)
        is_light = (file + rank) % 2 == 1
        color = DARK_SQUARE if is_light else LIGHT_SQUARE
        label = small_font.render(str(rank + 1), True, color)
        screen.blit(label, (4, row * SQUARE_SIZE + 2))


def choose_mode(screen, font, big_font):
    small_font_for_controls = pygame.font.SysFont("arial", 15)
    labels = [("vs Bot", "bot"), ("vs Human (local)", "human")]
    button_w, button_h = 260, 60
    gap = 80
    start_y = 260
    buttons = {}
    for i, (label, value) in enumerate(labels):
        rect = pygame.Rect(BOARD_SIZE // 2 - button_w // 2, start_y + i * gap, button_w, button_h)
        buttons[value] = (label, rect)

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            if event.type == pygame.MOUSEBUTTONDOWN:
                for value, (label, rect) in buttons.items():
                    if rect.collidepoint(event.pos):
                        return value

        screen.fill(BAYLOR_GREEN)
        pygame.draw.rect(screen, BAYLOR_GOLD, (0, 0, BOARD_SIZE, 6))
        title = big_font.render("Baylor Chess", True, BAYLOR_GOLD)
        screen.blit(title, title.get_rect(center=(BOARD_SIZE // 2, 130)))
        subtitle = font.render("Choose how you want to play", True, WHITE_TEXT)
        screen.blit(subtitle, subtitle.get_rect(center=(BOARD_SIZE // 2, 185)))

        mouse_pos = pygame.mouse.get_pos()
        for value, (label, rect) in buttons.items():
            hovered = rect.collidepoint(mouse_pos)
            shadow_rect = rect.move(0, 3)
            pygame.draw.rect(screen, (0, 30, 13), shadow_rect, border_radius=14)
            color = WHITE_TEXT if hovered else BAYLOR_GOLD
            pygame.draw.rect(screen, color, rect, border_radius=14)
            text = font.render(label, True, BAYLOR_GREEN)
            screen.blit(text, text.get_rect(center=rect.center))

        controls_title = small_font_for_controls.render("Controls", True, BAYLOR_GOLD)
        screen.blit(controls_title, controls_title.get_rect(center=(BOARD_SIZE // 2, 440)))
        for i, line in enumerate(CONTROLS_LINES):
            label = small_font_for_controls.render(line, True, WHITE_TEXT)
            screen.blit(label, label.get_rect(center=(BOARD_SIZE // 2, 465 + i * 20)))

        pygame.display.flip()
        pygame.time.delay(16)


def choose_timer_control(screen, font, big_font):
    labels = [("10 min per side", 600), ("No timer", None)]
    button_w, button_h = 260, 60
    gap = 80
    start_y = 260
    buttons = {}
    for i, (label, value) in enumerate(labels):
        rect = pygame.Rect(BOARD_SIZE // 2 - button_w // 2, start_y + i * gap, button_w, button_h)
        buttons[label] = (value, rect)

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            if event.type == pygame.MOUSEBUTTONDOWN:
                for label, (value, rect) in buttons.items():
                    if rect.collidepoint(event.pos):
                        return value

        screen.fill(BAYLOR_GREEN)
        title = big_font.render("Baylor Chess", True, BAYLOR_GOLD)
        screen.blit(title, title.get_rect(center=(BOARD_SIZE // 2, 150)))
        subtitle = font.render("Choose a time control", True, WHITE_TEXT)
        screen.blit(subtitle, subtitle.get_rect(center=(BOARD_SIZE // 2, 200)))

        mouse_pos = pygame.mouse.get_pos()
        for label, (value, rect) in buttons.items():
            hovered = rect.collidepoint(mouse_pos)
            color = WHITE_TEXT if hovered else BAYLOR_GOLD
            pygame.draw.rect(screen, color, rect, border_radius=10)
            text = font.render(label, True, BAYLOR_GREEN)
            screen.blit(text, text.get_rect(center=rect.center))

        pygame.display.flip()
        pygame.time.delay(16)


def text_input_screen(screen, font, big_font, prompt, max_len=20):
    text = ""
    box_rect = pygame.Rect(BOARD_SIZE // 2 - 160, 250, 320, 50)
    clock = pygame.time.Clock()

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_RETURN:
                    return text.strip()
                elif event.key == pygame.K_BACKSPACE:
                    text = text[:-1]
                elif len(text) < max_len and event.unicode.isprintable():
                    text += event.unicode

        screen.fill(BAYLOR_GREEN)
        title = big_font.render("Baylor Chess", True, BAYLOR_GOLD)
        screen.blit(title, title.get_rect(center=(BOARD_SIZE // 2, 120)))
        prompt_label = font.render(prompt, True, WHITE_TEXT)
        screen.blit(prompt_label, prompt_label.get_rect(center=(BOARD_SIZE // 2, 190)))

        pygame.draw.rect(screen, BAYLOR_GOLD, box_rect, border_radius=8)
        text_surface = font.render(text, True, BAYLOR_GREEN)
        screen.blit(text_surface, (box_rect.x + 12, box_rect.y + 14))

        hint = font.render("Press Enter to continue", True, WHITE_TEXT)
        screen.blit(hint, hint.get_rect(center=(BOARD_SIZE // 2, 340)))

        pygame.display.flip()
        clock.tick(30)


def choose_difficulty(screen, font, big_font):
    desc_font = pygame.font.SysFont("arial", 14)
    labels = ["Easy", "Medium", "Hard", "Bear"]
    button_w, button_h = 220, 60
    gap = 85
    start_y = 220
    buttons = {}
    for i, label in enumerate(labels):
        rect = pygame.Rect(BOARD_SIZE // 2 - button_w // 2, start_y + i * gap, button_w, button_h)
        buttons[label] = rect

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            if event.type == pygame.MOUSEBUTTONDOWN:
                for label, rect in buttons.items():
                    if rect.collidepoint(event.pos):
                        return label

        screen.fill(BAYLOR_GREEN)
        title = big_font.render("Baylor Chess", True, BAYLOR_GOLD)
        screen.blit(title, title.get_rect(center=(BOARD_SIZE // 2, 110)))
        subtitle = font.render("Choose your opponent", True, WHITE_TEXT)
        screen.blit(subtitle, subtitle.get_rect(center=(BOARD_SIZE // 2, 160)))

        mouse_pos = pygame.mouse.get_pos()
        for label, rect in buttons.items():
            hovered = rect.collidepoint(mouse_pos)
            color = WHITE_TEXT if hovered else BAYLOR_GOLD
            pygame.draw.rect(screen, color, rect, border_radius=14)
            text = font.render(label, True, BAYLOR_GREEN)
            screen.blit(text, text.get_rect(center=rect.center))
            desc = desc_font.render(DIFFICULTY_INFO[label], True, WHITE_TEXT)
            screen.blit(desc, desc.get_rect(center=(rect.centerx, rect.bottom + 14)))

        pygame.display.flip()
        pygame.time.delay(16)


def coin_flip_screen(screen, font, big_font, player1, player2):
    flip_btn = pygame.Rect(BOARD_SIZE // 2 - 110, 260, 220, 60)
    continue_btn = pygame.Rect(BOARD_SIZE // 2 - 110, 340, 220, 50)
    result = None

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            if event.type == pygame.MOUSEBUTTONDOWN:
                if result is None and flip_btn.collidepoint(event.pos):
                    result = random.choice([(player1, player2), (player2, player1)])
                elif result is not None and continue_btn.collidepoint(event.pos):
                    return {chess.WHITE: result[0], chess.BLACK: result[1]}

        screen.fill(BAYLOR_GREEN)
        title = big_font.render("Baylor Chess", True, BAYLOR_GOLD)
        screen.blit(title, title.get_rect(center=(BOARD_SIZE // 2, 130)))
        mouse_pos = pygame.mouse.get_pos()

        if result is None:
            subtitle = font.render("Flip a coin to decide colors", True, WHITE_TEXT)
            screen.blit(subtitle, subtitle.get_rect(center=(BOARD_SIZE // 2, 190)))
            hovered = flip_btn.collidepoint(mouse_pos)
            color = WHITE_TEXT if hovered else BAYLOR_GOLD
            pygame.draw.rect(screen, color, flip_btn, border_radius=12)
            label = font.render("Flip Coin", True, BAYLOR_GREEN)
            screen.blit(label, label.get_rect(center=flip_btn.center))
        else:
            white_name, black_name = result
            res_text = font.render(f"{white_name} is White  -  {black_name} is Black", True, BAYLOR_GOLD)
            screen.blit(res_text, res_text.get_rect(center=(BOARD_SIZE // 2, 220)))
            hovered = continue_btn.collidepoint(mouse_pos)
            color = WHITE_TEXT if hovered else BAYLOR_GOLD
            pygame.draw.rect(screen, color, continue_btn, border_radius=12)
            label = font.render("Continue", True, BAYLOR_GREEN)
            screen.blit(label, label.get_rect(center=continue_btn.center))

        pygame.display.flip()
        pygame.time.delay(16)


def get_player_setup(screen, font, big_font):
    mode = choose_mode(screen, font, big_font)

    if mode == "bot":
        player_name = text_input_screen(screen, font, big_font, "Enter your name:") or "Player"
        difficulty = choose_difficulty(screen, font, big_font)
        names = {
            HUMAN_COLOR: player_name,
            not HUMAN_COLOR: f"Bot ({difficulty})",
        }
        time_control = choose_timer_control(screen, font, big_font)
        return mode, difficulty, names, time_control

    player1 = text_input_screen(screen, font, big_font, "Player 1, enter your name:") or "Player 1"
    player2 = text_input_screen(screen, font, big_font, "Player 2, enter your name:") or "Player 2"
    names = coin_flip_screen(screen, font, big_font, player1, player2)
    time_control = choose_timer_control(screen, font, big_font)
    return mode, None, names, time_control


def outcome_title(outcome, names):
    if outcome.winner is None:
        return "Draw!"
    winner_name = names[outcome.winner]
    if outcome.termination == chess.Termination.CHECKMATE:
        return f"Checkmate! {winner_name} wins"
    return f"{winner_name} wins"


REVIEW_BTN_RECT = pygame.Rect(BOARD_SIZE // 2 - 110, BOARD_SIZE // 2 + 60, 220, 44)


def draw_end_banner(screen, big_font, font, board, names, time_forfeit_winner, resigned_color, mouse_pos):
    overlay = pygame.Surface((BOARD_SIZE, BOARD_SIZE), pygame.SRCALPHA)
    overlay.fill((0, 0, 0, 160))
    screen.blit(overlay, (0, 0))

    if time_forfeit_winner is not None:
        title_text = f"Time's up! {names[time_forfeit_winner]} wins"
        subtitle_text = "Win on time"
    elif resigned_color is not None:
        winner = not resigned_color
        title_text = f"{names[resigned_color]} resigns - {names[winner]} wins"
        subtitle_text = "Win by resignation"
    else:
        outcome = board.outcome()
        title_text = outcome_title(outcome, names)
        subtitle_text = str(outcome.termination).split(".")[-1].replace("_", " ").title()

    title = big_font.render(title_text, True, BAYLOR_GOLD)
    screen.blit(title, title.get_rect(center=(BOARD_SIZE // 2, BOARD_SIZE // 2 - 40)))
    subtitle = font.render(subtitle_text, True, WHITE_TEXT)
    screen.blit(subtitle, subtitle.get_rect(center=(BOARD_SIZE // 2, BOARD_SIZE // 2 - 5)))

    hovered = REVIEW_BTN_RECT.collidepoint(mouse_pos)
    color = WHITE_TEXT if hovered else BAYLOR_GOLD
    pygame.draw.rect(screen, color, REVIEW_BTN_RECT, border_radius=10)
    label = font.render("Game Review", True, BAYLOR_GREEN)
    screen.blit(label, label.get_rect(center=REVIEW_BTN_RECT.center))


def status_text(board, names, is_bot_turn, is_live):
    if board.is_game_over():
        outcome = board.outcome()
        if outcome.winner is None:
            return "Game over: Draw"
        return f"Game over: {names[outcome.winner]} wins"
    turn_name = names[board.turn]
    base = f"{turn_name} thinking..." if is_bot_turn else f"{turn_name} to move"
    if not is_live:
        base += "   (reviewing past move - press -> or click Live to resume)"
    return base


def draw_status(screen, font, text):
    pygame.draw.rect(screen, STATUS_BG, (0, BOARD_SIZE, screen.get_width(), STATUS_HEIGHT))
    label = font.render(text, True, STATUS_TEXT)
    screen.blit(label, (10, BOARD_SIZE + 8))


def move_uci(board, from_sq, to_sq):
    piece = board.piece_at(from_sq)
    uci = chess.square_name(from_sq) + chess.square_name(to_sq)
    if piece and piece.piece_type == chess.PAWN and chess.square_rank(to_sq) in (0, 7):
        uci += "q"
    return uci


def get_captured_piece(board, move):
    """Must be called BEFORE board.push(move)."""
    if board.is_en_passant(move):
        return chess.Piece(chess.PAWN, not board.turn)
    return board.piece_at(move.to_square)


def record_move(board, move, history):
    """Pushes move onto board and appends a snapshot to history."""
    captured = get_captured_piece(board, move)
    san = board.san(move)
    move_uci_str = move.uci()
    captured_white = list(history[-1]["captured_white"])
    captured_black = list(history[-1]["captured_black"])
    board.push(move)
    if captured:
        if captured.color == chess.WHITE:
            captured_white.append(captured.piece_type)
        else:
            captured_black.append(captured.piece_type)
    history.append({
        "fen": board.fen(),
        "san": san,
        "move_uci": move_uci_str,
        "captured_white": captured_white,
        "captured_black": captured_black,
    })


# --- Sidebar layout constants (shared by drawing and click hit-testing) ---
SB_X = BOARD_SIZE
SB_CLOCK_TOP = 10
SB_LIST_TOP = 90
SB_ROW_H = 22
SB_VISIBLE_ROWS = 11
SB_NUM_X = 10
SB_WHITE_X = 50
SB_BLACK_X = 165
SB_CAP_ICON = 24
SB_CAP1_Y = SB_LIST_TOP + SB_VISIBLE_ROWS * SB_ROW_H + 30
SB_CAP2_Y = SB_CAP1_Y + 22 + SB_CAP_ICON * 2 + 20
SB_LIVE_BTN = pygame.Rect(SB_X + 10, BOARD_SIZE - 50, SIDEBAR_WIDTH - 20, 36)
SB_RESIGN_BTN = pygame.Rect(SB_X + 10, BOARD_SIZE - 96, SIDEBAR_WIDTH - 20, 36)


def format_clock(seconds):
    if seconds is None:
        return "--:--"
    seconds = max(0, int(seconds))
    return f"{seconds // 60:02d}:{seconds % 60:02d}"


def sidebar_scroll_for_view(view_index):
    row_of_view = (view_index - 1) // 2 if view_index >= 1 else 0
    return row_of_view


def clamp_scroll(scroll_offset, view_index):
    row = sidebar_scroll_for_view(view_index)
    if row < scroll_offset:
        scroll_offset = row
    elif row >= scroll_offset + SB_VISIBLE_ROWS:
        scroll_offset = row - SB_VISIBLE_ROWS + 1
    return max(0, scroll_offset)


def draw_resign_button(screen, small_font, mouse_pos):
    hovered = SB_RESIGN_BTN.collidepoint(mouse_pos)
    color = (220, 90, 90) if hovered else (170, 60, 60)
    pygame.draw.rect(screen, color, SB_RESIGN_BTN, border_radius=8)
    label = small_font.render("Resign", True, WHITE_TEXT)
    screen.blit(label, label.get_rect(center=SB_RESIGN_BTN.center))


def draw_sidebar(screen, font, small_font, small_images, history, view_index, scroll_offset,
                  clocks, names, active_color):
    pygame.draw.rect(screen, SIDEBAR_BG, (SB_X, 0, SIDEBAR_WIDTH, BOARD_SIZE))

    white_secs = clocks[chess.WHITE] if clocks else None
    black_secs = clocks[chess.BLACK] if clocks else None
    white_low = white_secs is not None and white_secs < 30
    black_low = black_secs is not None and black_secs < 30

    w_color = BAD_COLOR if white_low else (BAYLOR_GOLD if active_color == chess.WHITE else WHITE_TEXT)
    b_color = BAD_COLOR if black_low else (BAYLOR_GOLD if active_color == chess.BLACK else WHITE_TEXT)

    w_label = small_font.render(f"{names[chess.WHITE]}: {format_clock(white_secs)}", True, w_color)
    screen.blit(w_label, (SB_X + 12, SB_CLOCK_TOP))
    b_label = small_font.render(f"{names[chess.BLACK]}: {format_clock(black_secs)}", True, b_color)
    screen.blit(b_label, (SB_X + 12, SB_CLOCK_TOP + 22))

    title = font.render("Move List", True, BAYLOR_GOLD)
    screen.blit(title, (SB_X + 12, SB_CLOCK_TOP + 50))

    sans = [e["san"] for e in history[1:]]
    total_rows = (len(sans) + 1) // 2 if sans else 0

    for r in range(SB_VISIBLE_ROWS):
        row_index = scroll_offset + r
        if row_index >= total_rows:
            break
        y = SB_LIST_TOP + r * SB_ROW_H
        num_label = small_font.render(f"{row_index + 1}.", True, WHITE_TEXT)
        screen.blit(num_label, (SB_X + SB_NUM_X, y))

        white_ply = row_index * 2 + 1
        black_ply = row_index * 2 + 2

        if white_ply < len(history):
            color = BAYLOR_GOLD if view_index == white_ply else WHITE_TEXT
            text = small_font.render(sans[white_ply - 1], True, color)
            screen.blit(text, (SB_X + SB_WHITE_X, y))
        if black_ply < len(history):
            color = BAYLOR_GOLD if view_index == black_ply else WHITE_TEXT
            text = small_font.render(sans[black_ply - 1], True, color)
            screen.blit(text, (SB_X + SB_BLACK_X, y))

    snapshot = history[view_index]

    label1 = small_font.render("White captured:", True, WHITE_TEXT)
    screen.blit(label1, (SB_X + 10, SB_CAP1_Y))
    for i, pt in enumerate(snapshot["captured_black"]):
        col, row = i % 9, i // 9
        icon = small_images[(chess.BLACK, pt)]
        screen.blit(icon, (SB_X + 10 + col * SB_CAP_ICON, SB_CAP1_Y + 22 + row * SB_CAP_ICON))

    label2 = small_font.render("Black captured:", True, WHITE_TEXT)
    screen.blit(label2, (SB_X + 10, SB_CAP2_Y))
    for i, pt in enumerate(snapshot["captured_white"]):
        col, row = i % 9, i // 9
        icon = small_images[(chess.WHITE, pt)]
        screen.blit(icon, (SB_X + 10 + col * SB_CAP_ICON, SB_CAP2_Y + 22 + row * SB_CAP_ICON))

    is_live = (view_index == len(history) - 1)
    btn_color = WHITE_TEXT if is_live else BAYLOR_GOLD
    pygame.draw.rect(screen, btn_color, SB_LIVE_BTN, border_radius=8)
    label = small_font.render("Live" if is_live else "Return to Live", True, BAYLOR_GREEN)
    screen.blit(label, label.get_rect(center=SB_LIVE_BTN.center))


def sidebar_click(pos, history, scroll_offset):
    """Returns a new view_index if the click hit something navigable, else None."""
    if SB_LIVE_BTN.collidepoint(pos):
        return len(history) - 1

    x, y = pos
    if x < SB_X or y >= SB_LIST_TOP + SB_VISIBLE_ROWS * SB_ROW_H:
        return None
    if y < SB_LIST_TOP:
        return None

    row_on_screen = (y - SB_LIST_TOP) // SB_ROW_H
    row_index = scroll_offset + row_on_screen

    if x < SB_X + SB_BLACK_X:
        ply = row_index * 2 + 1
    else:
        ply = row_index * 2 + 2

    if 0 < ply < len(history):
        return ply
    return None


# ---------------------------------------------------------------------------
# Game review: analysis, JSON export, and dedicated review screen
# ---------------------------------------------------------------------------

def cost_tier(cost):
    if cost <= GOOD_THRESHOLD:
        return "good"
    elif cost <= OK_THRESHOLD:
        return "ok"
    return "bad"


REVIEW_TIER_COLORS = {"good": GOOD_COLOR, "ok": OK_COLOR, "bad": BAD_COLOR}


def analyze_game(history, progress_callback=None):
    """
    Walks the whole game and, for each move actually played, compares it
    against the best move our own alpha-beta search (positional_eval) could
    find at REVIEW_DEPTH. This is a lightweight built-in analyzer, not a
    dedicated chess engine, but it's consistent with the bots already used
    in-game.
    """
    eval_history = [positional_eval(chess.Board(history[0]["fen"]), chess.WHITE)]
    move_costs = []
    total = len(history) - 1

    for i in range(1, len(history)):
        board_before = chess.Board(history[i - 1]["fen"])
        mover = board_before.turn
        played_uci = history[i]["move_uci"]
        played_move = chess.Move.from_uci(played_uci)

        best_score = float("-inf")
        best_move = None
        played_score = None

        for move in board_before.legal_moves:
            board_before.push(move)
            score = -alpha_beta(board_before, REVIEW_DEPTH - 1, float("-inf"), float("inf"),
                                 not mover, positional_eval)
            board_before.pop()
            if score > best_score:
                best_score = score
                best_move = move
            if move == played_move:
                played_score = score

        cost = max(0, best_score - played_score)
        move_costs.append({
            "ply": i,
            "san": history[i]["san"],
            "played_uci": played_uci,
            "best_uci": best_move.uci(),
            "cost": cost,
            "mover": mover,
        })
        eval_history.append(positional_eval(chess.Board(history[i]["fen"]), chess.WHITE))

        if progress_callback:
            progress_callback(i, total)

    return {"eval_history": eval_history, "move_costs": move_costs}


def save_game_review(analysis, names):
    os.makedirs("game_reviews", exist_ok=True)
    filename = os.path.join("game_reviews", f"game_{int(time.time())}.json")
    payload = {
        "names": {"white": names[chess.WHITE], "black": names[chess.BLACK]},
        "eval_history": analysis["eval_history"],
        "move_costs": [
            {
                "ply": mc["ply"],
                "san": mc["san"],
                "played_uci": mc["played_uci"],
                "best_uci": mc["best_uci"],
                "cost": mc["cost"],
                "mover": "white" if mc["mover"] == chess.WHITE else "black",
            }
            for mc in analysis["move_costs"]
        ],
    }
    with open(filename, "w") as f:
        json.dump(payload, f, indent=2)
    return filename


def run_analysis_with_progress(screen, font, big_font, history):
    total = len(history) - 1

    def callback(i, total_moves):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
        screen.fill(BAYLOR_GREEN)
        title = big_font.render("Analyzing Game...", True, BAYLOR_GOLD)
        screen.blit(title, title.get_rect(center=(screen.get_width() // 2, BOARD_SIZE // 2 - 40)))
        bar_w, bar_h = 400, 30
        bar_x = screen.get_width() // 2 - bar_w // 2
        bar_y = BOARD_SIZE // 2
        pygame.draw.rect(screen, WHITE_TEXT, (bar_x, bar_y, bar_w, bar_h), 2)
        fill_w = int(bar_w * i / total_moves) if total_moves else bar_w
        pygame.draw.rect(screen, BAYLOR_GOLD, (bar_x, bar_y, fill_w, bar_h))
        pygame.display.flip()

    if total <= 0:
        return {"eval_history": [positional_eval(chess.Board(history[0]["fen"]), chess.WHITE)], "move_costs": []}

    return analyze_game(history, progress_callback=callback)


EVAL_GRAPH_HEIGHT = 80
REVIEW_LIST_ROWS = 11
REVIEW_ROW_H = 22
REVIEW_EXIT_BTN = pygame.Rect(SB_X + 10, BOARD_SIZE - 50, SIDEBAR_WIDTH - 20, 36)


def draw_eval_graph(screen, eval_history, view_index, rect):
    pygame.draw.rect(screen, SIDEBAR_BG, rect)
    if len(eval_history) < 2:
        return
    max_abs = max(200, max(abs(e) for e in eval_history))
    mid_y = rect.y + rect.height // 2
    pygame.draw.line(screen, WHITE_TEXT, (rect.x, mid_y), (rect.x + rect.width, mid_y), 1)

    points = []
    for i, e in enumerate(eval_history):
        x = rect.x + int(i / (len(eval_history) - 1) * rect.width)
        y = mid_y - int((e / max_abs) * (rect.height // 2 - 4))
        points.append((x, y))
    pygame.draw.lines(screen, BAYLOR_GOLD, False, points, 2)

    vx = rect.x + int(view_index / (len(eval_history) - 1) * rect.width)
    pygame.draw.line(screen, WHITE_TEXT, (vx, rect.y), (vx, rect.y + rect.height), 1)


def draw_review_list(screen, small_font, history, move_costs, view_index, scroll_offset, top_y):
    sans = [e["san"] for e in history[1:]]
    total_rows = (len(sans) + 1) // 2 if sans else 0

    for r in range(REVIEW_LIST_ROWS):
        row_index = scroll_offset + r
        if row_index >= total_rows:
            break
        y = top_y + r * REVIEW_ROW_H
        num_label = small_font.render(f"{row_index + 1}.", True, WHITE_TEXT)
        screen.blit(num_label, (SB_X + SB_NUM_X, y))

        white_ply = row_index * 2 + 1
        black_ply = row_index * 2 + 2

        if white_ply < len(history):
            tier = cost_tier(move_costs[white_ply - 1]["cost"])
            color = BAYLOR_GOLD if view_index == white_ply else REVIEW_TIER_COLORS[tier]
            text = small_font.render(sans[white_ply - 1], True, color)
            screen.blit(text, (SB_X + SB_WHITE_X, y))
        if black_ply < len(history):
            tier = cost_tier(move_costs[black_ply - 1]["cost"])
            color = BAYLOR_GOLD if view_index == black_ply else REVIEW_TIER_COLORS[tier]
            text = small_font.render(sans[black_ply - 1], True, color)
            screen.blit(text, (SB_X + SB_BLACK_X, y))

    return total_rows


def review_click(pos, history, scroll_offset, list_top):
    if REVIEW_EXIT_BTN.collidepoint(pos):
        return "exit"
    x, y = pos
    if x < SB_X or y < list_top or y >= list_top + REVIEW_LIST_ROWS * REVIEW_ROW_H:
        return None
    row_on_screen = (y - list_top) // REVIEW_ROW_H
    row_index = scroll_offset + row_on_screen
    if x < SB_X + SB_BLACK_X:
        ply = row_index * 2 + 1
    else:
        ply = row_index * 2 + 2
    if 0 < ply < len(history):
        return ply
    return None


def draw_review_highlights(screen, view_index, move_costs):
    if view_index == 0:
        return
    mc = move_costs[view_index - 1]
    played = chess.Move.from_uci(mc["played_uci"])
    for sq in (played.from_square, played.to_square):
        x, y = square_to_pixel(sq)
        pygame.draw.rect(screen, HIGHLIGHT, (x, y, SQUARE_SIZE, SQUARE_SIZE), 4)
    if mc["best_uci"] != mc["played_uci"]:
        best = chess.Move.from_uci(mc["best_uci"])
        for sq in (best.from_square, best.to_square):
            x, y = square_to_pixel(sq)
            pygame.draw.rect(screen, SUGGEST_COLOR, (x, y, SQUARE_SIZE, SQUARE_SIZE), 3)


def run_review_screen(screen, font, small_font, big_font, images, history, analysis):
    move_costs = analysis["move_costs"]
    eval_history = analysis["eval_history"]
    view_index = len(history) - 1
    scroll_offset = 0
    clock = pygame.time.Clock()

    graph_rect = pygame.Rect(SB_X, 10, SIDEBAR_WIDTH, EVAL_GRAPH_HEIGHT)
    list_top = graph_rect.bottom + 34

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_LEFT:
                    view_index = max(0, view_index - 1)
                elif event.key == pygame.K_RIGHT:
                    view_index = min(len(history) - 1, view_index + 1)
                elif event.key == pygame.K_ESCAPE:
                    running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                result = review_click(event.pos, history, scroll_offset, list_top)
                if result == "exit":
                    running = False
                elif result is not None:
                    view_index = result

        row = (view_index - 1) // 2 if view_index >= 1 else 0
        if row < scroll_offset:
            scroll_offset = row
        elif row >= scroll_offset + REVIEW_LIST_ROWS:
            scroll_offset = row - REVIEW_LIST_ROWS + 1
        scroll_offset = max(0, scroll_offset)

        view_board = chess.Board(history[view_index]["fen"])
        screen.fill(BAYLOR_GREEN)
        draw_board(screen, view_board, images, None, [])
        draw_coordinates(screen, small_font)
        draw_review_highlights(screen, view_index, move_costs)

        pygame.draw.rect(screen, SIDEBAR_BG, (SB_X, 0, SIDEBAR_WIDTH, BOARD_SIZE))
        draw_eval_graph(screen, eval_history, view_index, graph_rect)
        title = font.render("Move Review", True, BAYLOR_GOLD)
        screen.blit(title, (SB_X + 12, graph_rect.bottom + 4))
        draw_review_list(screen, small_font, history, move_costs, view_index, scroll_offset, list_top)

        pygame.draw.rect(screen, WHITE_TEXT, REVIEW_EXIT_BTN, border_radius=8)
        exit_label = small_font.render("Exit Review", True, BAYLOR_GREEN)
        screen.blit(exit_label, exit_label.get_rect(center=REVIEW_EXIT_BTN.center))

        status_str = f"Eval: {eval_history[view_index] / 100:+.2f}"
        if view_index >= 1:
            mc = move_costs[view_index - 1]
            if mc["best_uci"] != mc["played_uci"]:
                prev_board = chess.Board(history[view_index - 1]["fen"])
                best_san = prev_board.san(chess.Move.from_uci(mc["best_uci"]))
                status_str += f"   Best was {best_san}"
        draw_status(screen, font, status_str)

        pygame.display.flip()
        clock.tick(30)


def main():
    board = chess.Board()

    pygame.init()
    pygame.display.set_caption("Baylor Chess")
    screen = pygame.display.set_mode(MENU_WINDOW_SIZE)
    font = pygame.font.SysFont("arial", 20)
    small_font = pygame.font.SysFont("arial", 16)
    big_font = pygame.font.SysFont("arial", 36, bold=True)
    images = load_piece_images(SQUARE_SIZE)
    small_images = load_piece_images(SB_CAP_ICON)

    mode, difficulty, names, time_control = get_player_setup(screen, font, big_font)
    bot_color = (not HUMAN_COLOR) if mode == "bot" else None
    get_bot_move = BOT_MOVE_FUNCS[difficulty] if mode == "bot" else None

    screen = pygame.display.set_mode(GAME_WINDOW_SIZE)

    history = [{"fen": board.fen(), "san": None, "move_uci": None, "captured_white": [], "captured_black": []}]
    view_index = 0
    scroll_offset = 0

    clocks = {chess.WHITE: time_control, chess.BLACK: time_control} if time_control is not None else None
    time_forfeit_winner = None
    resigned_color = None

    selected_square = None
    legal_targets = []
    clock = pygame.time.Clock()
    running = True

    while running:
        dt = clock.tick(30)
        over = board.is_game_over() or time_forfeit_winner is not None or resigned_color is not None
        is_bot_turn = mode == "bot" and board.turn == bot_color
        is_live = view_index == len(history) - 1

        if clocks is not None and not over:
            clocks[board.turn] -= dt / 1000.0
            if clocks[board.turn] <= 0:
                clocks[board.turn] = 0
                time_forfeit_winner = not board.turn
                over = True

        mouse_pos = pygame.mouse.get_pos()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_LEFT:
                    view_index = max(0, view_index - 1)
                    selected_square, legal_targets = None, []
                elif event.key == pygame.K_RIGHT:
                    view_index = min(len(history) - 1, view_index + 1)
                    selected_square, legal_targets = None, []
                elif event.key == pygame.K_HOME:
                    view_index = 0
                    selected_square, legal_targets = None, []
                elif event.key == pygame.K_END:
                    view_index = len(history) - 1
                    selected_square, legal_targets = None, []

            elif event.type == pygame.MOUSEBUTTONDOWN:
                if not over and event.pos[0] >= SB_X and SB_RESIGN_BTN.collidepoint(event.pos):
                    resigned_color = board.turn if mode == "human" else HUMAN_COLOR
                elif over and REVIEW_BTN_RECT.collidepoint(event.pos):
                    analysis = run_analysis_with_progress(screen, font, big_font, history)
                    save_game_review(analysis, names)
                    run_review_screen(screen, font, small_font, big_font, images, history, analysis)
                elif event.pos[0] >= BOARD_SIZE:
                    new_index = sidebar_click(event.pos, history, scroll_offset)
                    if new_index is not None:
                        view_index = new_index
                        selected_square, legal_targets = None, []
                elif not over and not is_bot_turn and is_live:
                    square = pixel_to_square(event.pos)
                    if square is None:
                        continue

                    if selected_square is not None and square in legal_targets:
                        move = chess.Move.from_uci(move_uci(board, selected_square, square))
                        old_last = len(history) - 1
                        was_live = view_index == old_last
                        record_move(board, move, history)
                        if was_live:
                            view_index = len(history) - 1
                        selected_square, legal_targets = None, []
                    else:
                        piece = board.piece_at(square)
                        if piece and piece.color == board.turn:
                            selected_square = square
                            legal_targets = [m.to_square for m in board.legal_moves if m.from_square == square]
                        else:
                            selected_square, legal_targets = None, []

        if not running:
            break

        scroll_offset = clamp_scroll(scroll_offset, view_index)
        view_board = chess.Board(history[view_index]["fen"])

        draw_board(screen, view_board, images, selected_square if is_live else None,
                   legal_targets if is_live else [])
        draw_coordinates(screen, small_font)
        draw_sidebar(screen, font, small_font, small_images, history, view_index, scroll_offset,
                     clocks, names, board.turn)
        draw_status(screen, font, status_text(board, names, is_bot_turn, is_live))
        if not over:
            draw_resign_button(screen, small_font, mouse_pos)
        else:
            draw_end_banner(screen, big_font, font, board, names, time_forfeit_winner, resigned_color, mouse_pos)
        pygame.display.flip()

        if running and not over and is_bot_turn:
            pygame.time.delay(300)
            old_last = len(history) - 1
            was_live = view_index == old_last
            record_move(board, get_bot_move(board, bot_color), history)
            if was_live:
                view_index = len(history) - 1

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()